version: "3.8"

x-agql: &agql
    image: agql.js:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
    volumes:
        - ..:/app

services:
    server:
        <<: *agql
        container_name: agql
        command: yarn start
        ports:
            - 4000:4000
