version: "3.8"

x-agql: &agql
    image: agql.js:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
    volumes:
        - ..:/app
        - db:/db
        - node_modules:/app/node_modules
        - parcel_cache:/app/.parcel-cache

services:
    backend:
        <<: *agql
        container_name: agql_server_backend
        command: yarn server
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        environment:
            - DEBUG=${DEBUG}
            - SERVER_PORT=${BACKEND_PORT}
            - SERVER_MODE=backend
            - SCHEMA_CONFIG_DB_PATH=${SCHEMA_CONFIG_DB_PATH}

    graphql:
        <<: *agql
        container_name: agql_server_graphql
        command: yarn server
        ports:
            - ${GRAPHQL_PORT}:${GRAPHQL_PORT}
        secrets:
            - DB_ROOT_PASSWORD
        environment:
            - DEBUG=${DEBUG}
            - SERVER_PORT=${GRAPHQL_PORT}
            - SERVER_MODE=graphql
            - SCHEMA_CONFIG_DB_PATH=${SCHEMA_CONFIG_DB_PATH}
            - GRAPHQL_DB_HOST=${GRAPHQL_DB_HOST}
            - GRAPHQL_DB_DATABASE=${GRAPHQL_DB_DATABASE}
            - GRAPHQL_DB_USERNAME=${GRAPHQL_DB_USERNAME}
            - GRAPHQL_DB_PASSWORD_FILE=${GRAPHQL_DB_PASSWORD_FILE}

    admin:
        <<: *agql
        container_name: agql_admin
        command: yarn admin -p ${ADMIN_PORT}
        ports:
            - ${ADMIN_PORT}:${ADMIN_PORT}
        environment:
            - BACKEND_GQL_API_URL=${BACKEND_GQL_API_URL}
            - COMPILE_RELAY=1

    db:
        image: mariadb
        container_name: ${GRAPHQL_DB_HOST}
        secrets:
            - DB_ROOT_PASSWORD
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PASSWORD
            - MARIADB_DATABASE=${GRAPHQL_DB_DATABASE}
            - MARIADB_USER=${GRAPHQL_DB_USERNAME}
            - MARIADB_PASSWORD_FILE=${GRAPHQL_DB_PASSWORD_FILE}

    adminer:
        image: adminer
        container_name: agql_adminer
        ports:
            - 8080:8080
        environment:
            - ADMINER_DEFAULT_SERVER=${GRAPHQL_DB_HOST}

volumes:
    db:
        name: agqldb
    node_modules:
        name: agqlnodemod
    parcel_cache:
        name: agqlparcelcache
    dbdata:
        name: agqldbdata

secrets:
    DB_ROOT_PASSWORD:
        file: ./secrets/DB_PWD
