version: "3.8"

x-agql: &agql
    image: agql.js:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
    volumes:
        - ..:/app
        - db:/db
        - node_modules:/app/node_modules

services:
    backend:
        <<: *agql
        container_name: agql_backend
        command: yarn server
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        environment:
            - DEBUG=${DEBUG}
            - SERVER_PORT=${BACKEND_PORT}
            - SERVER_MODE=all

    admin:
        <<: *agql
        container_name: agql_admin
        command: yarn admin -p ${ADMIN_PORT}
        ports:
            - ${ADMIN_PORT}:${ADMIN_PORT}

volumes:
    db:
        name: agqldb
    node_modules:
        name: agqlnodemod
