version: "3.8"

x-agql: &agql
    image: agql.js:latest
    build:
        context: ..
        dockerfile: docker/Dockerfile
    volumes:
        - ..:/app
        - db:/db
        - node_modules:/app/node_modules

services:
    server:
        <<: *agql
        container_name: agql
        command: yarn server
        ports:
            - 4000:4000

    admin:
        <<: *agql
        container_name: agql_admin
        command: yarn admin
        ports:
            - 1234:1234

volumes:
    db:
        name: agqldb
    node_modules:
        name: agqlnodemod
